import streamlit as st
import os
import subprocess
import re
from io import BytesIO
import fitz  # PyMuPDF
import docx
from PIL import Image
import numpy as np
from ddgs import DDGS

# Imports for LLMs
import ollama
from openai import OpenAI
import anthropic
import uuid

try:
    from google import genai
    GOOGLE_GENAI_AVAILABLE = True
except ImportError:
    GOOGLE_GENAI_AVAILABLE = False
    try:
        import google.genai as google_genai_old
        GOOGLE_GENAI_OLD_AVAILABLE = True
    except ImportError:
        GOOGLE_GENAI_OLD_AVAILABLE = False

# Conditional Import for PaddleOCR
try:
    from paddleocr import PaddleOCR
    PADDLE_AVAILABLE = True
except ImportError:
    PADDLE_AVAILABLE = False
except Exception:
    PADDLE_AVAILABLE = False

# --- Global Config ---
st.set_page_config(page_title="AI Resume Builder", layout="wide")

_PDFLATEX_CHECKED = False
_PDFLATEX_AVAILABLE = False
_PDFLATEX_ERROR = "pdflatex not found. Please ensure MikTeX or TeX Live is installed and in your PATH."

# --- Helper Functions ---

def _escape_ampersands_outside_tabular(body):
    """
    Escapes bare & characters in the LaTeX document body, but only outside
    tabular/tabularx/tabular* environments where & is a column separator.
    """
    tabular_pattern = re.compile(
        r'(\\begin\{tabular[x*]?\}.*?\\end\{tabular[x*]?\})',
        re.DOTALL
    )
    parts = tabular_pattern.split(body)
    result = []
    for i, part in enumerate(parts):
        if i % 2 == 1:
            # Odd indices are the captured tabular blocks — leave untouched
            result.append(part)
        else:
            # Even indices are plain text — escape bare &
            result.append(re.sub(r'(?<!\\)&', r'\\&', part))
    return ''.join(result)


def clean_latex_code(text):
    """
    Cleans the LaTeX code generated by the LLM.

    Args:
        text (str): The raw text output from the LLM.

    Returns:
        str: The cleaned LaTeX code, stripped of markdown blocks and with
             context-aware ampersand escaping (plain text only, not tabular).
    """
    # Remove markdown code blocks if present
    text = re.sub(r'```latex', '', text, flags=re.IGNORECASE)
    text = re.sub(r'```', '', text)

    # Escape & in body only (not preamble), skipping tabular column separators
    if "\\begin{document}" in text:
        parts = text.split("\\begin{document}")
        preamble = parts[0]
        # Rejoin all parts after the first split (handles unlikely duplicate marker)
        body = "\\begin{document}".join(parts[1:])
        body = _escape_ampersands_outside_tabular(body)
        text = preamble + "\\begin{document}" + body

    return text.strip()


def validate_latex_safety(text):
    """
    Validates generated LaTeX to block known dangerous primitives.

    Args:
        text (str): Generated LaTeX source.

    Returns:
        tuple: (bool, str) indicating if text is safe and an error message.
    """
    blocked_patterns = [
        # Direct shell / file primitives
        r'\\write18\b',
        r'\\openout\b',
        r'\\read(?:\b|\d)',
        r'\\usepackage\s*\{shellesc\}',
        # Shell-pipe read via \input{|cmd}
        r'\\input\s*\{\s*\|',
        # Category-code manipulation (can redefine any character meaning)
        r'\\catcode\b',
        # Dynamic command construction (can synthesise blocked commands at runtime)
        r'\\csname\b',
        # Explicit shell-escape flag (should never appear in generated source)
        r'--shell-escape',
    ]
    for pattern in blocked_patterns:
        if re.search(pattern, text, flags=re.IGNORECASE):
            return False, f"Unsafe LaTeX command detected: {pattern}"
    return True, ""

def compile_latex(tex_filename):
    """
    Compiles a LaTeX file to PDF using pdflatex.
    
    Args:
        tex_filename (str): The path to the .tex file to compile.
        
    Returns:
        tuple: (bool, str) - (Success status, Output message or error log).
    """
    # Check if pdflatex is available in the system PATH (once per process)
    global _PDFLATEX_CHECKED, _PDFLATEX_AVAILABLE, _PDFLATEX_ERROR
    if not _PDFLATEX_CHECKED:
        try:
            subprocess.run(["pdflatex", "--version"], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            _PDFLATEX_AVAILABLE = True
        except FileNotFoundError:
            _PDFLATEX_AVAILABLE = False
        _PDFLATEX_CHECKED = True

    if not _PDFLATEX_AVAILABLE:
        return False, _PDFLATEX_ERROR

    compile_cmd = ["pdflatex", "-interaction=nonstopmode", tex_filename]
    try:
        # Run pdflatex TWICE: first pass writes .aux, second resolves \pageref*{LastPage}
        for _ in range(2):
            result = subprocess.run(
                compile_cmd,
                capture_output=True,
                text=True,
                check=False
            )
            if result.returncode != 0:
                return False, result.stdout + "\n" + result.stderr

        return True, "Compilation successful."
    except FileNotFoundError:
        return False, _PDFLATEX_ERROR
    except Exception as e:
        return False, str(e)

@st.cache_data(ttl=3600)
def get_market_research(role):
    """
    Performs a DuckDuckGo search to find resume trends for a specific job role.
    Results are cached for 1 hour to avoid repeated network requests (PERF-05).

    Args:
        role (str): The job title to research (e.g., "Data Scientist").

    Returns:
        str: A summary of top search results or an error message.
    """
    if not role:
        return "No role specified."
    try:
        query = f"latest resume trends and keywords for {role} 2025"
        with DDGS() as ddgs:
            # Fetch top 3 results
            results = list(ddgs.text(query, max_results=3))
        
        summary = "\n".join([f"- {r['title']}: {r['body']}" for r in results])
        return summary
    except Exception as e:
        return f"Market research failed: {e}"

@st.cache_data(ttl=60)
def get_ollama_models():
    """
    Fetches the list of available local Ollama models.
    Results are cached for 60 s to avoid repeated HTTP requests per rerun (PERF-01).

    Returns:
        list: A list of model names (str). Returns a default fallback list on failure.
    """
    try:
        models_info = ollama.list()
        # Handle different response formats (object vs dict) depending on library version
        if hasattr(models_info, 'models'):
            return [m.model for m in models_info.models]
        if 'models' in models_info:
            return [m['name'] for m in models_info['models']]
        return ["llama3", "mistral", "glm-4.7-flash"]
    except Exception:
        return ["llama3", "mistral", "glm-4.7-flash"] # Fallback

# --- Configuration (Sidebar) ---

def get_llm_config():
    """
    Renders the Sidebar configuration UI and returns the user settings.
    
    Returns:
        dict: A dictionary containing 'provider', 'model', 'api_key', 'base_url', 
              and vision-related settings.
    """
    st.sidebar.title("⚙️ Configuration")
    
    # 1. Brain (LLM) Settings
    st.sidebar.subheader("Brain (LLM)")
    provider = st.sidebar.selectbox("LLM Provider", ["Ollama", "OpenAI", "Google Gemini", "Anthropic"])
    
    config = {"provider": provider}
    
    # Render fields specific to the selected provider
    if provider == "Ollama":
        models = get_ollama_models()
        config['model'] = st.sidebar.selectbox("Select Model", models)
        config['api_key'] = None
        config['base_url'] = None
    elif provider == "OpenAI":
        config['api_key'] = st.sidebar.text_input("OpenAI API Key", type="password")
        config['base_url'] = st.sidebar.text_input("Base URL", "https://api.openai.com/v1")
        config['model'] = st.sidebar.text_input("Model Name", "gpt-4o")
    elif provider == "Google Gemini":
        # BUG-04/SEC-01: prefer OS env var so the key is never typed into the UI
        _env_key = os.environ.get("GOOGLE_API_KEY", "")
        _input_key = st.sidebar.text_input(
            "Gemini API Key",
            value=_env_key,
            type="password",
            help="Leave blank to use GOOGLE_API_KEY environment variable."
        )
        config['api_key'] = _input_key or _env_key
        config['model'] = "gemini-2.5-flash"
    elif provider == "Anthropic":
        config['api_key'] = st.sidebar.text_input("Anthropic API Key", type="password")
        config['model'] = "claude-4-5-sonnet-latest"

    # 2. Eyes (Vision/OCR) Settings
    st.sidebar.subheader("Eyes (Vision/OCR)")
    vision_options = ["Same as LLM", "PaddleOCR", "Google Gemini (Free Tier)", "Local Ollama Vision"]
    vision_provider = st.sidebar.selectbox("Vision Provider", vision_options)
    config['vision_provider'] = vision_provider
    
    # Credentials/Models for Vision if different from LLM
    if vision_provider == "Google Gemini (Free Tier)" and provider != "Google Gemini":
        config['vision_api_key'] = st.sidebar.text_input("Vision: Gemini API Key", type="password", key="vis_gemini")
    elif vision_provider == "Local Ollama Vision":
        ollama_models = get_ollama_models()
        config['vision_model'] = st.sidebar.selectbox("Select Vision Model", ollama_models, help="Select a vision-capable model (e.g., llava, moondream, deepseek-vl)")
    
    return config


# PERF-02: Cache PaddleOCR model so weights are loaded only once per session
@st.cache_resource
def _get_paddle_ocr():
    """Return a cached PaddleOCR instance to avoid repeated model loading."""
    return PaddleOCR(use_angle_cls=True, lang='en', show_log=False)


# --- Universal Smart Parser ---

def smart_extract_text(input_data, is_file, config):
    """
    Extracts text from a file (PDF, DOCX, Image) or returns raw text.
    Implements a multi-layered approach:
    1. Text Extraction (fast, for native PDFs/Docs)
    2. Vision/OCR (fallback for scanned PDFs or images)
    
    Args:
        input_data: The file object or string to process.
        is_file (bool): True if input_data is a file object.
        config (dict): Configuration dictionary containing provider settings.
        
    Returns:
        str: The extracted text content.
    """
    if not is_file:
        return str(input_data) # Return raw text directly

    uploaded_file = input_data
    file_type = uploaded_file.name.split('.')[-1].lower()
    text_content = ""
    extraction_errors = []
    
    # Reset file pointer to beginning
    uploaded_file.seek(0)
    file_bytes = uploaded_file.read()

    # --- Layer 1: Fast Text Extraction (Native) ---
    # For PDFs, open fitz ONCE and reuse the object in Layer 2 (PERF-03 - no double open)
    pdf_doc = None
    if file_type == 'pdf':
        try:
            pdf_doc = fitz.open(stream=file_bytes, filetype="pdf")
            for page in pdf_doc:
                text_content += page.get_text() + "\n"
            # If we got substantial text, assume it's not a scanned PDF
            if len(text_content.strip()) > 50:
                if hasattr(pdf_doc, "close"):
                    pdf_doc.close()
                pdf_doc = None
                return text_content
        except Exception as e:  # BUG-08: typed exception replaces bare except
            extraction_errors.append(f"PDF text extraction failed: {e}")
    elif file_type == 'docx':
        try:
            doc = docx.Document(BytesIO(file_bytes))
            text_content = "\n".join([p.text for p in doc.paragraphs])
            if len(text_content.strip()) > 50:
                return text_content
        except Exception as e:  # BUG-08: typed exception replaces bare except
            extraction_errors.append(f"DOCX extraction failed: {e}")
    elif file_type == 'txt':
        return file_bytes.decode('utf-8', errors='ignore')

    # --- Layer 2: Image Conversion (for Scanned Docs) ---
    image = None
    if file_type == 'pdf':
        doc = None
        try:
            # Reuse the already-opened pdf_doc from Layer 1 (PERF-03)
            doc = pdf_doc if pdf_doc is not None else fitz.open(stream=file_bytes, filetype="pdf")
            if len(doc) > 0:
                pix = doc[0].get_pixmap()
                image = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        except Exception as e:  # BUG-08: typed exception replaces bare except
            extraction_errors.append(f"PDF image conversion failed: {e}")
        finally:
            if doc is not None:
                if hasattr(doc, "close"):
                    doc.close()
            pdf_doc = None
    elif file_type in ['png', 'jpg', 'jpeg']:
        image = Image.open(BytesIO(file_bytes))

    if image is None:
        if extraction_errors:
            return "Failed to extract text or convert document to image. " + " | ".join(extraction_errors)
        return "Failed to extract text or convert document to image."

    # --- Layer 3: Vision/OCR Extraction ---
    
    # Determine the active provider for vision tasks
    vis_prov = config['vision_provider']
    active_provider = config['provider'] if vis_prov == "Same as LLM" else vis_prov
    
    # Use vision key if available, else fallback to main key
    api_key = config.get('vision_api_key') or config.get('api_key')
    
    st.info(f"Scanned document detected. Engaging Vision Layer: {active_provider}")

    # 1. PaddleOCR (Local Offline OCR)
    if active_provider == "PaddleOCR":
        if PADDLE_AVAILABLE:
            try:
                ocr = _get_paddle_ocr()  # PERF-02: cached model via @st.cache_resource
                res = ocr.ocr(np.array(image), cls=True)
                # BUG-09: Guard against None or empty result (blank/unrecognised pages)
                if not res or not res[0]:
                    return "PaddleOCR: No text detected in image."
                return "\n".join([
                    line[1][0] for line in res[0]
                    if line is not None and len(line) > 1 and line[1]
                ])
            except Exception as e:
                return f"PaddleOCR Error: {e}"
        else:
            return "PaddleOCR not installed or compatible."

    # 2. Google Gemini (Vision)
    if "Google Gemini" in active_provider:
        if not api_key: return "Vision Error: Missing Gemini API Key."
        try:
            if GOOGLE_GENAI_AVAILABLE:
                client = genai.Client(api_key=api_key)
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=["Transcribe this resume image exactly.", image]
                )
                return response.text
            elif GOOGLE_GENAI_OLD_AVAILABLE:
                google_genai_old.configure(api_key=api_key)
                model = google_genai_old.GenerativeModel('gemini-2.5-flash')
                response = model.generate_content(["Transcribe this resume image exactly.", image])
                return response.text
        except Exception as e: return f"Gemini Vision Error: {e}"

    # 3. OpenAI (Vision)
    if active_provider == "OpenAI":
        if not api_key: return "Vision Error: Missing OpenAI API Key."
        try:
            import base64
            buffered = BytesIO()
            image.save(buffered, format="PNG")
            img_str = base64.b64encode(buffered.getvalue()).decode()
            
            client = OpenAI(api_key=api_key, base_url=config.get('base_url'))
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "user", "content": [
                        {"type": "text", "text": "Transcribe this resume image exactly."},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_str}"}}
                    ]}
                ]
            )
            return response.choices[0].message.content
        except Exception as e: return f"OpenAI Vision Error: {e}"

    # 4. Anthropic (Vision)
    if active_provider == "Anthropic":
        if not api_key: return "Vision Error: Missing Anthropic API Key."
        try:
            import base64
            buffered = BytesIO()
            image.save(buffered, format="PNG")
            img_str = base64.b64encode(buffered.getvalue()).decode()
            
            client = anthropic.Anthropic(api_key=api_key)
            response = client.messages.create(
                model="claude-3-5-sonnet-latest", max_tokens=4096,
                messages=[
                    {"role": "user", "content": [
                        {"type": "text", "text": "Transcribe this resume image exactly."},
                        {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": img_str}}
                    ]}
                ]
            )
            return response.content[0].text
        except Exception as e: return f"Anthropic Vision Error: {e}"

    # 5. Local Ollama Vision
    if active_provider == "Local Ollama Vision":
        try:
            buffered = BytesIO()
            image.save(buffered, format="PNG")
            img_bytes = buffered.getvalue()

            vision_model = config.get('vision_model', 'llava')  # Fallback to llava

            response = ollama.chat(
                model=vision_model,
                messages=[{
                    'role': 'user',
                    'content': 'Transcribe the text from this resume image exactly as it appears, preserving structure.',
                    'images': [img_bytes]
                }]
            )
            # BUG-03: ollama >= 0.2 returns Pydantic object, not dict
            return response.message.content
        except Exception as e:
            return f"Ollama Vision Error: {e}"

    return "No suitable Vision Provider found (or DeepSeek-OCR placeholder selected)."


# --- Main Application Flow ---

def main():
    """
    Main execution logic for the Streamlit application.
    Handles UI rendering, state management, and workflow orchestration.
    """
    config = get_llm_config()
    st.title("🚀 AI Resume Builder")

    # Session State Initialization - Preserves data across reruns
    if 'step' not in st.session_state: st.session_state.step = 1
    if 'extracted_text' not in st.session_state: st.session_state.extracted_text = ""
    if 'research' not in st.session_state: st.session_state.research = ""
    if 'target_role' not in st.session_state: st.session_state.target_role = ""
    if 'job_desc' not in st.session_state: st.session_state.job_desc = ""
    
    # State for Resume Generation Results
    if 'generated_success' not in st.session_state: st.session_state.generated_success = False
    if 'generated_pdf_data' not in st.session_state: st.session_state.generated_pdf_data = None
    if 'generated_tex_data' not in st.session_state: st.session_state.generated_tex_data = None
    if 'generation_error' not in st.session_state: st.session_state.generation_error = None
    if 'session_id' not in st.session_state: st.session_state.session_id = uuid.uuid4().hex

    # --- Step 1: Input & Analysis ---
    if st.session_state.step == 1:
        st.header("Step 1: Profile & Target")
        
        col1, col2 = st.columns(2)
        with col1:
            target_role = st.text_input("Target Role", value=st.session_state.target_role, placeholder="e.g. Senior DevOps Engineer")
        with col2:
            job_desc = st.text_area("Job Description (Optional)", value=st.session_state.job_desc, height=100)
            
        st.subheader("Input Source")
        input_method = st.radio("Choose Input Method", ["File Upload", "Raw Text"], horizontal=True)
        
        user_input = None
        is_file = False
        
        if input_method == "File Upload":
            user_input = st.file_uploader("Upload Resume (PDF/DOCX/Image)", type=['pdf', 'docx', 'png', 'jpg', 'txt'])
            is_file = True
        else:
            user_input = st.text_area("Paste Resume Text Here", height=200)
            is_file = False

        if st.button("Analyze Profile", type="primary"):
            if not user_input or not target_role:
                st.error("Please provide both a Resume and a Target Role.")
            else:
                with st.spinner("Analyzing Document & Market Trends..."):
                    # 1. Extraction: Parse the uploaded file or text
                    extracted_text = smart_extract_text(user_input, is_file, config)
                    if (
                        not extracted_text
                        or extracted_text.startswith("Failed to extract text")
                        or extracted_text.startswith("Vision Error:")
                        or extracted_text.startswith("PaddleOCR Error:")
                        or extracted_text.startswith("Gemini Vision Error:")
                        or extracted_text.startswith("OpenAI Vision Error:")
                        or extracted_text.startswith("Anthropic Vision Error:")
                        or extracted_text.startswith("Ollama Vision Error:")
                        or extracted_text == "PaddleOCR not installed or compatible."
                    ):
                        st.error(extracted_text)
                        return
                    st.session_state.extracted_text = extracted_text
                    
                    # 2. Market Research: Fetch trends for the role
                    research = get_market_research(target_role)
                    st.session_state.research = research
                    
                    # 3. Save State & Advance to Step 2
                    st.session_state.target_role = target_role
                    st.session_state.job_desc = job_desc
                    st.session_state.generated_success = False # Reset prev generation
                    st.session_state.step = 2
                    st.rerun()

    # --- Step 2: Review & Generate ---
    elif st.session_state.step == 2:
        st.header("Step 2: Review & Draft")
        
        # Navigation
        if st.button("⬅ Back to Input"):
            st.session_state.step = 1
            st.rerun()

        # Editable Fields
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Extracted Profile")
            st.caption("Edit this text to correct any parsing errors.")
            edited_profile = st.text_area("Profile Data", value=st.session_state.extracted_text, height=400, key="edit_profile")
            st.session_state.extracted_text = edited_profile
            
        with col2:
            st.subheader("Market Insights")
            st.caption("Key trends found for your role.")
            edited_research = st.text_area("Market Trends", value=st.session_state.research, height=400, key="edit_research")
            st.session_state.research = edited_research

        st.markdown("---")
        
        # Generation Button
        if st.button("Draft Resume (Generate LaTeX)", type="primary", use_container_width=True):
            with st.spinner("Generating LaTeX Resume... (This may take a minute)"):
                try:
                    # Load Template
                    try:
                        # BUG-07: explicit utf-8 to avoid UnicodeDecodeError on Windows
                        with open("template.tex", "r", encoding="utf-8") as f:
                            template_content = f.read()
                    except FileNotFoundError:
                        st.error("template.tex not found!")
                        st.stop()

                    # Construct Prompt for the LLM
                    system_prompt = "You are an expert resume writer and LaTeX developer."
                    user_prompt = f"""
                    Generate a complete LaTeX resume based on the data below.
                    
                    **1. User Profile:**
                    {st.session_state.extracted_text}
                    
                    **2. Target Role:** {st.session_state.target_role}
                    
                    **3. Job Description:**
                    {st.session_state.job_desc}
                    
                    **4. Market Trends:**
                    {st.session_state.research}
                    
                    **5. LaTeX Template:**
                    {template_content}
                    
                    **INSTRUCTIONS:**
                    - Fill the template with the user's info, tailored to the role/JD.
                    - Use keywords from Market Trends.
                    - **CRITICAL**: Escape special LaTeX chars (e.g. use \\& for &, \\% for %).
                    - Output ONLY valid LaTeX code.
                    - Do NOT remove packages/preamble.
                    """
                    
                    generated_latex = ""
                    prov = config['provider']
                    
                    # Call the selected LLM Provider
                    if prov == "Ollama":
                        resp = ollama.chat(model=config['model'], messages=[
                            {'role': 'system', 'content': system_prompt},
                            {'role': 'user', 'content': user_prompt}
                        ])
                        # BUG-03: ollama >= 0.2 returns Pydantic object, not dict
                        generated_latex = resp.message.content
                        
                    elif prov == "OpenAI":
                        if not config['api_key']: raise ValueError("Missing OpenAI API Key")
                        client = OpenAI(api_key=config['api_key'], base_url=config['base_url'])
                        resp = client.chat.completions.create(
                            model=config['model'],
                            messages=[{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': user_prompt}]
                        )
                        generated_latex = resp.choices[0].message.content
                        
                    elif prov == "Google Gemini":
                        if not config['api_key']: raise ValueError("Missing Gemini API Key")
                        if GOOGLE_GENAI_AVAILABLE:
                            client = genai.Client(api_key=config['api_key'])
                            resp = client.models.generate_content(model=config['model'], contents=system_prompt + "\n" + user_prompt)
                            generated_latex = resp.text
                        elif GOOGLE_GENAI_OLD_AVAILABLE:
                            google_genai_old.configure(api_key=config['api_key'])
                            model = google_genai_old.GenerativeModel(config['model'])
                            resp = model.generate_content(system_prompt + "\n" + user_prompt)
                            generated_latex = resp.text
                            
                    elif prov == "Anthropic":
                        if not config['api_key']: raise ValueError("Missing Anthropic API Key")
                        client = anthropic.Anthropic(api_key=config['api_key'])
                        resp = client.messages.create(
                            model=config['model'], max_tokens=4096,
                            messages=[{'role': 'user', 'content': system_prompt + "\n\n" + user_prompt}]
                        )
                        generated_latex = resp.content[0].text

                    # BUG-06: Guard against empty LLM output before writing to disk
                    if not generated_latex:
                        raise ValueError(
                            "LLM returned empty output. Check provider config, "
                            "API key, and model selection."
                        )

                    # Clean the output code
                    generated_latex = clean_latex_code(generated_latex)
                    if not generated_latex.strip():
                        raise ValueError("Generated LaTeX is empty after cleaning.")

                    is_safe, safety_error = validate_latex_safety(generated_latex)
                    if not is_safe:
                        raise ValueError(safety_error)

                    session_file_base = f"generated_resume_{st.session_state.session_id}"
                    tex_filename = f"{session_file_base}.tex"
                    pdf_filename = f"{session_file_base}.pdf"

                    # Save to file
                    with open(tex_filename, "w", encoding="utf-8") as f:
                        f.write(generated_latex)
                        
                    # Compile to PDF
                    success, msg = compile_latex(tex_filename)
                    
                    if success:
                        st.session_state.generated_success = True
                        st.session_state.generation_error = None
                        
                        # Read binary data into session state for persistent download buttons
                        pdf_read_path = pdf_filename if os.path.exists(pdf_filename) else "generated_resume.pdf"
                        tex_read_path = tex_filename if os.path.exists(tex_filename) else "generated_resume.tex"
                        with open(pdf_read_path, "rb") as f:
                            st.session_state.generated_pdf_data = f.read()
                        with open(tex_read_path, "rb") as f:
                            st.session_state.generated_tex_data = f.read()
                    else:
                        st.session_state.generated_success = False
                        st.session_state.generation_error = msg
                            
                except Exception as e:
                    st.session_state.generated_success = False
                    st.session_state.generation_error = f"Generation Error: {e}"

        # --- Display Results (Persistent) ---
        if st.session_state.generated_success:
            st.success("Resume Generated Successfully!")
            
            col_a, col_b = st.columns(2)
            with col_a:
                st.download_button(
                    label="Download PDF",
                    data=st.session_state.generated_pdf_data,
                    file_name="resume.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
            with col_b:
                st.download_button(
                    label="Download Source",
                    data=st.session_state.generated_tex_data,
                    file_name="resume.tex",
                    mime="text/plain",
                    use_container_width=True
                )
        
        elif st.session_state.generation_error:
            st.error("Compilation Failed")
            with st.expander("Error Log"):
                st.code(st.session_state.generation_error)
            # BUG-05: Guard open() — file only exists if LLM write succeeded
            debug_tex = f"generated_resume_{st.session_state.session_id}.tex"
            if os.path.exists(debug_tex) or os.path.exists("generated_resume.tex"):
                debug_tex_path = debug_tex if os.path.exists(debug_tex) else "generated_resume.tex"
                with open(debug_tex_path, "rb") as f:
                    st.download_button("Download Source (Debug)", f.read(), "resume.tex", "text/plain")

if __name__ == "__main__":
    main()
